services:
  - type: web
    name: django-image
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
